# ------------------------------------------------------------------------
#FROM ubuntu:16.04
FROM eleks/base-ubuntu-jdk8:8u201

WORKDIR /opt

#common packages
RUN	echo 'common packages' && \
	set -o errexit -o nounset && \
	apt-get update && \
	apt-get install -y --no-install-recommends curl unzip mc && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY    ./src /

#groovy
RUN echo "groovy-all" && \
	set -o errexit -o nounset && \
	mkdir /opt/gcli/lib && \
	curl "http://central.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.16/groovy-all-2.4.16.jar" > ./gcli/lib/groovy-all-2.4.16.jar && \
	curl "http://central.maven.org/maven2/org/yaml/snakeyaml/1.18/snakeyaml-1.18.jar"                  > ./gcli/lib/snakeyaml-1.18.jar && \
	chmod 775 /opt/gcli/bin/gcli && \
	ln -s "/opt/gcli/bin/gcli" /usr/bin/gcli && \
	echo 'gcli help' >> ~/.bash_history && \
	echo 'gcli deploy' >> ~/.bash_history

#curl "http://central.maven.org/maven2/org/apache/ant/ant/1.9.11/ant-1.9.11.jar"                    > ./gcli/lib/ant-1.9.11.jar && \
#curl "http://central.maven.org/maven2/org/apache/ant/ant-launcher/1.9.11/ant-launcher-1.9.11.jar"  > ./gcli/lib/ant-launcher-1.9.11.jar && \
# RUN echo 'GROOVY_HOME="$GROOVY_HOME"' >> /etc/environment

#where to copy during deploy 
ENV DEPLOY_TARGET=PLEASE_REDEFINE
#where deployment artifacts and config templates located 
ENV DEPLOY_SOURCE=/opt/deploy
#where template parameters located 
ENV CONF_SOURCE=/opt/conf

#suppose to map default deployment source locations to external volumes
#VOLUME  /opt/conf
#VOLUME  /opt/deploy

RUN	echo 'gcli version' && gcli version

# test deploy function
RUN	echo "------ Testing -------" && \
	set -o errexit -o nounset && \
	mkdir test && \
	export DEPLOY_TARGET=/opt/test && \
	export PERSISTENT_ROOT=/opt/.defaults && \
	gcli deploy &&\
	echo "------ Template output -------" && \
	cat /opt/test/readme.nfo && \
	echo "------ File output -----------" && \
	cat /opt/test/readme.txt && \
	echo "------ Properties ------------" && \
	cat /opt/.eval.json && \
	echo '\n------------------------------' && \
	rm -Rf /opt/test && \
	rm -f /opt/.eval.json


ENTRYPOINT set -eu && \
	gcli "version" && \
	gcli "help" && \
	/bin/bash
