# ------------------------------------------------------------------------
FROM openjdk:8u131-jdk-alpine

WORKDIR /opt


#common packages
RUN set -e && \
	apk update && \
	apk add --no-cache curl ca-certificates zip && \
	rm -rf /tmp/* /var/tmp/*

#copy gcli scripts
COPY    ./src /

#groovy
RUN	echo "groovy-all" && \
	set -o errexit -o nounset && \
	mkdir /opt/gcli/lib && \
	curl "http://central.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.16/groovy-all-2.4.16.jar" > ./gcli/lib/groovy-all-2.4.16.jar && \
	curl "http://central.maven.org/maven2/org/yaml/snakeyaml/1.18/snakeyaml-1.18.jar"                  > ./gcli/lib/snakeyaml-1.18.jar && \
	chmod 775 /opt/gcli/bin/gcli && \
	ln -s "/opt/gcli/bin/gcli" /usr/bin/gcli && \
    echo 'gcli help' >> ~/.ash_history && \
    echo 'gcli deploy' >> ~/.ash_history


#where to copy during deploy 
ENV DEPLOY_TARGET=PLEASE_REDEFINE
#where deployment artifacts and config templates located 
ENV DEPLOY_SOURCE=/opt/deploy
#where template parameters located 
ENV CONF_SOURCE=/opt/conf

#suppose to map default deployment source locations to external volumes
#VOLUME  /opt/conf
#VOLUME  /opt/deploy


RUN     alias ll='ls -la'
#set default shell to be user by kitematik
ENV     SHELL /bin/sh

# test java&groovy
RUN	echo 'gcli version' && gcli version

# test deploy function
RUN set -o errexit -o nounset && \
	echo "------ Testing -------" && \
	mkdir test && \
	export DEPLOY_TARGET=/opt/test && \
	export PERSISTENT_ROOT=/opt/.defaults && \
	gcli deploy &&\
	echo "------ Template output -------" && \
	cat /opt/test/readme.nfo && \
	echo "------ File output -----------" && \
	cat /opt/test/readme.txt && \
	echo "------ Properties ------------" && \
	cat /opt/.eval.json && \
	echo "\n------------------------------" && \
	rm -Rf /opt/test && \
	rm -f /opt/.eval.json


ENTRYPOINT set -eu && \
	gcli "version" && \
	gcli "help" && \
	/bin/bash
