# ------------------------------------------------------------------------
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ARG JAVA_VERSION=DEFINE

ENV PATH $PATH:$JAVA_HOME/bin:$GROOVY_HOME/bin

#common packages
RUN set -o errexit -o nounset && \
	echo common packages && \
	apt-get update && \
	apt-get install -y --no-install-recommends apt-utils && \
	apt-get install -y curl unzip mc iputils-ping inetutils-traceroute vim && \
	apt-get update


# java
RUN \
  set -e && \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  apt-get -y install software-properties-common && \
  add-apt-repository ppa:webupd8team/java -y && \
  apt-get update && \
  apt-get -y install oracle-java8-installer=${JAVA_VERSION}-1~webupd8~1 && \
  rm -rf /var/cache/oracle-jdk8-installer

#RUN echo 'JAVA_HOME="/usr/lib/jvm/java-8-oracle"' >> /etc/environment


# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# bash
RUN     alias ll='ls -la'
#set default shell bash
ENV     SHELL /bin/bash
ENV     BASH /bin/bash
# some ubuntu thing...
ENV     DEBIAN_FRONTEND newt

WORKDIR /opt

# test
RUN set -o errexit -o nounset && \
  java -version


ENTRYPOINT /bin/bash
