# ------------------------------------------------------------------------
# temporary layers
FROM ubuntu:16.04  as  worker

ARG JAVA_VERSION=DEFINE

# java
RUN	echo 'java setup' && \
	set -e && \
	apt-get update && \
	apt-get install -y --no-install-recommends apt-utils && \
	echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
	apt-get -y install software-properties-common && \
	add-apt-repository ppa:webupd8team/java -y && \
	apt-get update && \
	apt-get -y install oracle-java8-installer=${JAVA_VERSION}-1~webupd8~1 && \
	apt-get clean && \
	rm -rf /var/cache/oracle-jdk8-installer && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	rm -f /usr/lib/jvm/java-8-oracle/*src.zip && \
	rm -rf /usr/lib/jvm/java-8-oracle/man


## main layer
FROM ubuntu:16.04  as  master

# some ubuntu thing...
ENV	DEBIAN_FRONTEND newt
ENV	DEBIAN_FRONTEND noninteractive

ENV	JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV	PATH $PATH:$JAVA_HOME/bin
#RUN echo 'JAVA_HOME="/usr/lib/jvm/java-8-oracle"' >> /etc/environment


## copy main java folder
COPY --from=worker ${JAVA_HOME} ${JAVA_HOME}
COPY --from=worker /etc/java-8-oracle /etc/java-8-oracle
## copy main java folder
# COPY --from=worker /usr/bin/java /usr/bin/java



# bash
RUN	alias ll='ls -la'
#set default shell bash
ENV	SHELL /bin/bash
ENV	BASH /bin/bash

WORKDIR /opt

# test
RUN	echo 'java -version' && \
	set -o errexit -o nounset && \
	java -version


ENTRYPOINT /bin/bash
