version: '3.2'
    
services:
  # service name must correspond to ${ENV_PREFIX}ids${ENV_SUFFIX}
  # h2.docker.local:
    # ## this service is required if config for common databases used: conf/common-db
    # image: eleks/base-h2-1.2.140-wso2v3
    # ports:
      # - "${H2_PORT_HTTP}:1580"
      # - "${H2_PORT_TCP}:1521"
    # volumes:
      # ## where we will persist data
      # - ./h2-data:/opt/h2-data
  ids.docker.local:
    image: ${IMG_PREFIX}-wso2is-5.3.0
    # depends_on:
      # - h2.docker.local
    ports:
      - "${IDS_PORT_HTTPS}:9443"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=IDS
      # path to get configs 
      - CONF_SOURCE=${IDS_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${IDS_DEPLOY_SOURCE}
  idx.docker.local:
    image: ${IMG_PREFIX}-wso2is-analytics-5.3.0
    depends_on:
      - ids.docker.local
    ports:
      - "${IDX_PORT_HTTPS}:9443"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=IDX
      # path to get configs 
      - CONF_SOURCE=${IDX_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${IDX_DEPLOY_SOURCE}
  esb.docker.local:
    image: ${IMG_PREFIX}-wso2esb-4.9.0
    depends_on:
      - ids.docker.local
    ports:
      - "${ESB_PORT_MHTTPS}:9443"
      - "${ESB_PORT_MHTTP}:9763"
      - "${ESB_PORT_HTTPS}:8243"
      - "${ESB_PORT_HTTP}:8280"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=ESB
      # path to get configs 
      - CONF_SOURCE=${ESB_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${ESB_DEPLOY_SOURCE}

  bps.docker.local:
    image: ${IMG_PREFIX}-wso2bps-3.5.1
    depends_on:
      - ids.docker.local
    ports:
      - "${BPS_PORT_HTTPS}:9443"
      - "${BPS_PORT_HTTP}:9763"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=BPS
      # path to get configs 
      - CONF_SOURCE=${BPS_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${BPS_DEPLOY_SOURCE}
