version: '3.2'

services:
  # service name must correspond to ${ENV_PREFIX}ids${ENV_SUFFIX}
  ids.docker.local:
    image: eleks/base-wso2is-5.3.0
    ports:
      - "${PORT_IDS_HTTPS}:9443"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      #- ./myapp:/opt/wso2is-5.3.0/repository/deployment/server/jaggeryapps/myapp
    env_file:
      ## env variables defined for whole compose into container
      - .env
    environment:
      - ROLE=IDS
      # path to get configs 
      - CONF_SOURCE=${IDS_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${IDS_DEPLOY_SOURCE}
  idx.docker.local:
    image: eleks/base-wso2is-analytics-5.3.0
    ports:
      - "${PORT_IDX_HTTPS}:9443"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
    env_file:
      ## env variables defined for whole compose into container
      - .env
    environment:
      - ROLE=IDX
      # path to get configs 
      - CONF_SOURCE=${IDX_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${IDX_DEPLOY_SOURCE}
  esb.docker.local:
    image: eleks/base-wso2esb-4.9.0
    ports:
      - "${PORT_ESB_MHTTPS}:9443"
      - "${PORT_ESB_MHTTP}:9763"
      - "${PORT_ESB_HTTPS}:8243"
      - "${PORT_ESB_HTTP}:8280"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
    env_file:
      ## env variables defined for whole compose into container
      - .env
    environment:
      - ROLE=ESB
      # path to get configs 
      - CONF_SOURCE=${ESB_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${ESB_DEPLOY_SOURCE}

  bps.docker.local:
    image: eleks/base-wso2bps-3.5.1
    ports:
      - "${PORT_BPS_HTTPS}:9443"
      - "${PORT_BPS_HTTP}:9763"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
    env_file:
      ## env variables defined for whole compose into container
      - .env
    environment:
      - ROLE=BPS
      # path to get configs 
      - CONF_SOURCE=${BPS_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${BPS_DEPLOY_SOURCE}
