version: '3.2'
    
services:
  # service name must correspond to ${ENV_PREFIX}ids${ENV_SUFFIX}
  ids.docker.local:
    image: eleks/base-wso2is-5.3.0
    ports:
      - "${IDS_PORT_HTTPS}:9443"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=IDS
      # path to get configs 
      - CONF_SOURCE=${IDS_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${IDS_DEPLOY_SOURCE}
  idx.docker.local:
    image: eleks/base-wso2is-analytics-5.3.0
    ports:
      - "${IDX_PORT_HTTPS}:9443"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=IDX
      # path to get configs 
      - CONF_SOURCE=${IDX_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${IDX_DEPLOY_SOURCE}
  esb.docker.local:
    image: eleks/base-wso2esb-4.9.0
    ports:
      - "${ESB_PORT_MHTTPS}:9443"
      - "${ESB_PORT_MHTTP}:9763"
      - "${ESB_PORT_HTTPS}:8243"
      - "${ESB_PORT_HTTP}:8280"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=ESB
      # path to get configs 
      - CONF_SOURCE=${ESB_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${ESB_DEPLOY_SOURCE}

  bps.docker.local:
    image: eleks/base-wso2bps-3.5.1
    ports:
      - "${BPS_PORT_HTTPS}:9443"
      - "${BPS_PORT_HTTP}:9763"
    volumes:
      - ./conf:/opt/conf
      - ./deploy:/opt/deploy
      - ./templates:/opt/templates
    ## pass env variables defined for whole compose into container
    env_file: [".env"]
    ## link to extension-fields. see: https://docs.docker.com/compose/compose-file/#extension-fields
    extra_hosts: ["${EXTRA_HOST_1}"]
    environment:
      - ROLE=BPS
      # path to get configs 
      - CONF_SOURCE=${BPS_CONF_SOURCE}
      # path to get deploy artifacts 
      - DEPLOY_SOURCE=${BPS_DEPLOY_SOURCE}
